FROM node:22.16.0-alpine AS base

RUN npm i -g pnpm@10.11.1

FROM base AS dependencies

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml ./

RUN pnpm i

FROM base AS build 

WORKDIR /usr/src/app

COPY . .
COPY --from=dependencies /usr/src/app/node_modules  ./node_modules

RUN pnpm build
RUN pnpm prune --prod

FROM base AS deploy

USER 1000

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/package.json ./package.json

ENV DATABASE_URL="postgresql://docker:docker@localhost:5432/upload_test"
ENV CLOUDFLARE_ACCOUNT_ID=""
ENV CLOUDFLARE_ACCESS_KEY_ID=""
ENV CLOUDFLARE_SECRET_ACCESS_KEY=""
ENV CLOUDFLARE_BUCKET=""
ENV CLOUDFLARE_PUBLIC_URL="https://pub-e7e11137a3a64cfe930db171c7574079.r2.dev"

EXPOSE 3333

CMD ["pnpm", "start"]